"""Playwright Python template — encodes Playwright best practices."""

from __future__ import annotations

from test_forge.frameworks.base_template import BaseTemplate


class PlaywrightTemplate(BaseTemplate):
    """Generates Playwright Python test files.

    Uses sync API with pytest-playwright fixtures.
    Selector priority mirrors the crawler: data-test > id > aria > css.
    Navigation waits are added automatically when the LLM flags them.
    """

    framework_name = "playwright"

    # ------------------------------------------------------------------ #
    # Full file renderer                                                   #
    # ------------------------------------------------------------------ #

    def render(
        self,
        *,
        test_id: str,
        description: str,
        steps_code: list[str],
        base_url: str,
        imports_extra: list[str] | None = None,
    ) -> str:
        """Assemble a complete, runnable pytest-playwright test file."""
        safe_id = test_id.lower().replace(" ", "_")
        slug = self.slugify(description)
        func_name = f"test_{safe_id}_{slug}"

        extra = "\n".join(imports_extra) if imports_extra else ""
        body = "\n".join(f"    {line}" for line in steps_code)

        return f'''\
"""Generated by test-forge — do not edit manually."""

import re

import pytest
from playwright.sync_api import Page, expect
{extra}

BASE_URL = "{base_url}"


def {func_name}(page: Page) -> None:
    """{test_id} — {description}"""
{body}
'''

    def render_conftest(self, *, base_url: str) -> str:
        """Shared conftest.py: configures base_url and common fixtures."""
        return f'''\
"""Shared Playwright fixtures for test-forge generated tests."""

import pytest
from playwright.sync_api import Page

BASE_URL = "{base_url}"


@pytest.fixture(scope="session")
def base_url() -> str:
    return BASE_URL


@pytest.fixture
def logged_in_page(page: Page) -> Page:
    """Pre-authenticated page fixture for tests that require login."""
    page.goto(BASE_URL)
    page.fill("[data-test=\'username\']", "standard_user")
    page.fill("[data-test=\'password\']", "secret_sauce")
    page.click("[data-test=\'login-button\']")
    page.wait_for_url("**/inventory.html")
    return page
'''

    # ------------------------------------------------------------------ #
    # Action builders — each returns one line of Playwright Python code   #
    # ------------------------------------------------------------------ #

    def action_goto(self, url: str) -> str:
        return f'page.goto("{url}")'

    def action_fill(self, selector: str, value: str) -> str:
        return f'page.fill("{selector}", "{value}")'

    def action_click(self, selector: str) -> str:
        return f'page.click("{selector}")'

    def action_select(self, selector: str, value: str) -> str:
        return f'page.select_option("{selector}", "{value}")'

    def action_wait_navigation(self, url_pattern: str) -> str:
        # Use glob pattern so it works across environments
        return f'page.wait_for_url("**{url_pattern}")'

    def action_assert_url(self, url_pattern: str) -> str:
        return f'expect(page).to_have_url(re.compile(r"{url_pattern}"))'

    def action_assert_visible(self, selector: str) -> str:
        return f'expect(page.locator("{selector}")).to_be_visible()'

    def action_assert_text(self, selector: str, text: str) -> str:
        return f'expect(page.locator("{selector}")).to_contain_text("{text}")'

    def action_assert_not_visible(self, selector: str) -> str:
        # Used for negative tests — e.g. error message should NOT appear on success
        return f'expect(page.locator("{selector}")).not_to_be_visible()'
