"""
Unit tests for the Crawler Agent.

Unit tests use mock pages — no network required.
Integration tests hit real URLs — marked with @pytest.mark.integration.
Run integration tests with: pytest -m integration
"""

import pytest
from src.test_forge.agents.crawler_agent import (
    CrawlerAgent,
    _looks_auto_generated,
    get_best_selector,
)
from src.test_forge.core.models import CrawlResult, PageElement, PageMetadata


# ── Selector strategy tests ────────────────────────────────────────────────────
class TestSelectorStrategy:
    """Tests for get_best_selector — no browser needed."""

    def test_prefers_data_test_attribute(self):
        el = {
            "tag": "input",
            "id": "username",
            "name": "user",
            "type": "text",
            "placeholder": "",
            "text": "",
            "classes": [],
            "attributes": {"data-test": "username-field"},
        }
        selector, strategy = get_best_selector(el)
        assert "[data-test='username-field']" == selector
        assert strategy == "data-test"

    def test_uses_id_when_no_data_test(self):
        el = {
            "tag": "input",
            "id": "user-name",
            "name": "",
            "type": "text",
            "placeholder": "",
            "text": "",
            "classes": [],
            "attributes": {},
        }
        selector, strategy = get_best_selector(el)
        assert selector == "#user-name"
        assert strategy == "id"

    def test_uses_name_when_no_id(self):
        el = {
            "tag": "input",
            "id": "",
            "name": "username",
            "type": "text",
            "placeholder": "",
            "text": "",
            "classes": [],
            "attributes": {},
        }
        selector, strategy = get_best_selector(el)
        assert selector == "[name='username']"
        assert strategy == "name"

    def test_uses_placeholder_as_fallback(self):
        el = {
            "tag": "input",
            "id": "",
            "name": "",
            "type": "text",
            "placeholder": "Enter username",
            "text": "",
            "classes": [],
            "attributes": {},
        }
        selector, strategy = get_best_selector(el)
        assert selector == "[placeholder='Enter username']"
        assert strategy == "placeholder"

    def test_uses_button_text(self):
        el = {
            "tag": "button",
            "id": "",
            "name": "",
            "type": "button",
            "placeholder": "",
            "text": "Login",
            "classes": [],
            "attributes": {},
        }
        selector, strategy = get_best_selector(el)
        assert "Login" in selector
        assert strategy == "text"

    def test_prefers_data_testid(self):
        el = {
            "tag": "button",
            "id": "",
            "name": "",
            "type": "submit",
            "placeholder": "",
            "text": "Submit",
            "classes": [],
            "attributes": {"data-testid": "submit-btn"},
        }
        selector, strategy = get_best_selector(el)
        assert "[data-testid='submit-btn']" == selector
        assert strategy == "data-test"

    def test_skips_autogenerated_id(self):
        el = {
            "tag": "input",
            "id": "a3f9bc12ef45",
            "name": "email",
            "type": "email",
            "placeholder": "",
            "text": "",
            "classes": [],
            "attributes": {},
        }
        selector, strategy = get_best_selector(el)
        # Should skip the auto-generated ID and use name instead
        assert selector == "[name='email']"
        assert strategy == "name"


class TestAutoGeneratedDetection:
    """Tests for _looks_auto_generated heuristic."""

    def test_hex_string_is_auto_generated(self):
        assert _looks_auto_generated("a3f9bc12") is True

    def test_meaningful_id_is_not_auto_generated(self):
        assert _looks_auto_generated("user-name") is False
        assert _looks_auto_generated("login-button") is False
        assert _looks_auto_generated("password") is False

    def test_random_suffix_is_auto_generated(self):
        assert _looks_auto_generated("css-1a2b3c4d") is True

    def test_short_id_is_not_auto_generated(self):
        assert _looks_auto_generated("btn") is False


# ── CrawlResult model tests ────────────────────────────────────────────────────
class TestCrawlResultModel:
    """Tests for CrawlResult properties."""

    def _make_result(self) -> CrawlResult:
        return CrawlResult(
            url="https://example.com",
            metadata=PageMetadata(url="https://example.com"),
            elements=[
                PageElement(
                    tag="input", selector="#username", type="text", is_visible=True, is_enabled=True
                ),
                PageElement(
                    tag="input",
                    selector="#password",
                    type="password",
                    is_visible=True,
                    is_enabled=True,
                ),
                PageElement(
                    tag="button",
                    selector="#submit",
                    type="submit",
                    is_visible=True,
                    is_enabled=True,
                ),
                PageElement(
                    tag="input",
                    selector="#hidden",
                    type="hidden",
                    is_visible=False,
                    is_enabled=True,
                ),
            ],
        )

    def test_interactive_elements_filters_invisible(self):
        result = self._make_result()
        interactive = result.interactive_elements
        assert len(interactive) == 3
        assert all(e.is_visible for e in interactive)

    def test_inputs_returns_only_inputs(self):
        result = self._make_result()
        inputs = result.inputs
        assert len(inputs) == 3  # text, password, hidden
        assert all(e.tag == "input" for e in inputs)

    def test_buttons_returns_only_buttons(self):
        result = self._make_result()
        buttons = result.buttons
        assert len(buttons) == 1
        assert buttons[0].selector == "#submit"

    def test_failed_crawl_has_no_elements(self):
        result = CrawlResult(
            url="https://example.com",
            metadata=PageMetadata(url="https://example.com"),
            success=False,
            warnings=["Connection refused"],
        )
        assert result.success is False
        assert len(result.elements) == 0
        assert len(result.warnings) == 1


class TestPageElement:
    """Tests for PageElement model."""

    def test_default_values(self):
        el = PageElement(tag="input", selector="#test")
        assert el.type == ""
        assert el.is_visible is True
        assert el.is_enabled is True
        assert el.triggers_navigation is False
        assert el.attributes == {}

    def test_navigation_trigger(self):
        el = PageElement(tag="button", selector="#submit", triggers_navigation=True)
        assert el.triggers_navigation is True


# ── Integration tests (real browser) ──────────────────────────────────────────
@pytest.mark.integration
class TestCrawlerAgentIntegration:
    """
    Integration tests — hit real SauceDemo URL.
    Run with: pytest -m integration
    Skipped in normal CI runs.
    """

    def test_crawls_saucedemo_login_page(self):
        agent = CrawlerAgent()
        result = agent.run("https://www.saucedemo.com")
        assert result.success is True
        assert result.metadata.title != ""
        assert len(result.elements) > 0

    def test_detects_saucedemo_as_spa(self):
        agent = CrawlerAgent()
        result = agent.run("https://www.saucedemo.com")
        assert result.metadata.is_spa is True

    def test_finds_login_form_elements(self):
        agent = CrawlerAgent()
        result = agent.run("https://www.saucedemo.com")
        selectors = [e.selector for e in result.elements]
        # Should find username, password, login button
        assert any("user" in s.lower() or "username" in s.lower() for s in selectors)
        assert any("password" in s.lower() for s in selectors)

    def test_detects_auth_page(self):
        agent = CrawlerAgent()
        result = agent.run("https://www.saucedemo.com")
        assert result.metadata.has_auth is True

    def test_invalid_url_returns_failed_result(self):
        agent = CrawlerAgent()
        result = agent.run("https://this-url-does-not-exist-xyz.com")
        assert result.success is False
        assert len(result.warnings) > 0
