"""Unit tests for ValidatorAgent — all checks tested against inline source strings."""

from __future__ import annotations

from pathlib import Path

import pytest

from test_forge.agents.validator_agent import ValidationResult, ValidatorAgent

# ------------------------------------------------------------------ #
# Fixtures                                                             #
# ------------------------------------------------------------------ #


@pytest.fixture
def agent() -> ValidatorAgent:
    return ValidatorAgent()


# A minimal valid Playwright test
VALID_SOURCE = '''\
"""Generated by test-forge."""

import re

from playwright.sync_api import Page, expect

BASE_URL = "https://www.saucedemo.com"


def test_tc001_login_with_valid_credentials(page: Page) -> None:
    """TC001 — Login with valid credentials"""
    page.goto("https://www.saucedemo.com")
    page.fill("[data-test=\'username\']", "standard_user")
    page.fill("[data-test=\'password\']", "secret_sauce")
    page.click("[data-test=\'login-button\']")
    page.wait_for_url("**/inventory.html")
    expect(page).to_have_url(re.compile(r"/inventory.html"))
'''

# Source with syntax error
SYNTAX_ERROR_SOURCE = """\
from playwright.sync_api import Page

def test_tc001(page: Page) -> None:
    page.goto("https://example.com"
"""

# Source with no test function
NO_TEST_FUNCTION_SOURCE = """\
from playwright.sync_api import Page

def helper(page: Page) -> None:
    page.goto("https://example.com")
"""

# Source missing playwright import
NO_IMPORT_SOURCE = """\
def test_tc001(page) -> None:
    page.goto("https://example.com")
    page.fill("[data-test=\'username\']", "user")
"""

# Source with only pass in test body
EMPTY_BODY_SOURCE = '''\
from playwright.sync_api import Page

def test_tc001(page: Page) -> None:
    """TC001"""
    pass
'''

# Source with Selenium method
SELENIUM_SOURCE = """\
from playwright.sync_api import Page

def test_tc001(page: Page) -> None:
    element = page.find_element("#username")
    element.send_keys("user")
"""

# Source with LLM backtick artefact
BACKTICK_SOURCE = '''\
from playwright.sync_api import Page

def test_tc001(page: Page) -> None:
    """TC001"""
    page.goto("https://example.com")
    # ```
    page.fill("[data-test=\'username\']", "user")
'''

# Source with UNPARSED comment artefact
UNPARSED_SOURCE = """\
from playwright.sync_api import Page

def test_tc001(page: Page) -> None:
    # UNPARSED: hover: #element
    page.goto("https://example.com")
"""

# Source with UNKNOWN ACTION comment artefact
UNKNOWN_ACTION_SOURCE = """\
from playwright.sync_api import Page

def test_tc001(page: Page) -> None:
    # UNKNOWN ACTION: drag: #element
    page.goto("https://example.com")
"""

# Source with empty selector
EMPTY_SELECTOR_SOURCE = """\
from playwright.sync_api import Page

def test_tc001(page: Page) -> None:
    page.goto("https://example.com")
    page.fill("", "standard_user")
"""


# ------------------------------------------------------------------ #
# ValidationResult model                                               #
# ------------------------------------------------------------------ #


class TestValidationResult:
    def test_starts_valid(self) -> None:
        r = ValidationResult(filename="test.py")
        assert r.valid is True
        assert r.errors == []
        assert r.warnings == []

    def test_add_error_sets_invalid(self) -> None:
        r = ValidationResult(filename="test.py")
        r.add_error("something broke")
        assert r.valid is False
        assert "something broke" in r.errors

    def test_add_warning_keeps_valid(self) -> None:
        r = ValidationResult(filename="test.py")
        r.add_warning("minor issue")
        assert r.valid is True
        assert "minor issue" in r.warnings

    def test_multiple_errors(self) -> None:
        r = ValidationResult(filename="test.py")
        r.add_error("error 1")
        r.add_error("error 2")
        assert len(r.errors) == 2
        assert r.valid is False


# ------------------------------------------------------------------ #
# Level 1 — Syntax checks                                              #
# ------------------------------------------------------------------ #


class TestSyntaxCheck:
    def test_valid_source_passes(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(VALID_SOURCE)
        assert result.valid is True
        assert not any("Syntax" in e for e in result.errors)

    def test_syntax_error_detected(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(SYNTAX_ERROR_SOURCE)
        assert result.valid is False
        assert any("Syntax error" in e for e in result.errors)

    def test_empty_source_fails(self, agent: ValidatorAgent) -> None:
        # Empty file is valid Python but has no test function
        result = agent.validate_source("")
        assert not any("Syntax error" in e for e in result.errors)


# ------------------------------------------------------------------ #
# Level 2 — Structure checks                                           #
# ------------------------------------------------------------------ #


class TestStructureCheck:
    def test_valid_source_has_no_structural_errors(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(VALID_SOURCE)
        assert not any(
            kw in e
            for e in result.errors
            for kw in ["No test function", "Selenium", "Empty selector"]
        )

    def test_missing_test_function_is_error(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(NO_TEST_FUNCTION_SOURCE)
        assert result.valid is False
        assert any("No test function" in e for e in result.errors)

    def test_missing_playwright_import_is_warning(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(NO_IMPORT_SOURCE)
        assert any("Missing import" in w for w in result.warnings)
        # Should not be an error — file might still run
        assert not any("Missing import" in e for e in result.errors)

    def test_empty_test_body_is_warning(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(EMPTY_BODY_SOURCE)
        assert any("empty body" in w for w in result.warnings)

    def test_empty_test_body_does_not_fail(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(EMPTY_BODY_SOURCE)
        # Empty body is a warning, not an error — file is still runnable
        assert result.valid is True

    def test_selenium_method_is_error(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(SELENIUM_SOURCE)
        assert result.valid is False
        assert any("Selenium method" in e for e in result.errors)

    def test_selenium_find_element_detected(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(SELENIUM_SOURCE)
        assert any("find_element" in e for e in result.errors)

    def test_valid_source_no_selenium_errors(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(VALID_SOURCE)
        assert not any("Selenium" in e for e in result.errors)


# ------------------------------------------------------------------ #
# Level 3 — Content checks                                             #
# ------------------------------------------------------------------ #


class TestContentCheck:
    def test_valid_source_no_content_errors(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(VALID_SOURCE)
        assert not any(kw in e for e in result.errors for kw in ["artefact", "Empty selector"])

    def test_backtick_is_warning(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(BACKTICK_SOURCE)
        assert any("markdown fence" in w for w in result.warnings)

    def test_backtick_does_not_fail(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(BACKTICK_SOURCE)
        assert result.valid is True

    def test_unparsed_comment_is_error(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(UNPARSED_SOURCE)
        assert result.valid is False
        assert any("artefact" in e for e in result.errors)

    def test_unknown_action_comment_is_error(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(UNKNOWN_ACTION_SOURCE)
        assert result.valid is False
        assert any("artefact" in e for e in result.errors)

    def test_empty_selector_is_error(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(EMPTY_SELECTOR_SOURCE)
        assert result.valid is False
        assert any("Empty selector" in e for e in result.errors)

    def test_line_number_in_error(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(UNPARSED_SOURCE)
        assert any("Line " in e for e in result.errors)

    def test_backtick_line_number_in_warning(self, agent: ValidatorAgent) -> None:
        result = agent.validate_source(BACKTICK_SOURCE)
        assert any("Line " in w for w in result.warnings)


# ------------------------------------------------------------------ #
# validate_file — file-based tests                                     #
# ------------------------------------------------------------------ #


class TestValidateFile:
    def test_valid_file_passes(self, agent: ValidatorAgent, tmp_path: Path) -> None:
        f = tmp_path / "test_tc001.py"
        f.write_text(VALID_SOURCE, encoding="utf-8")
        result = agent.validate_file(str(f))
        assert result.valid is True

    def test_missing_file_is_error(self, agent: ValidatorAgent) -> None:
        result = agent.validate_file("/nonexistent/path/test_tc001.py")
        assert result.valid is False
        assert any("File not found" in e for e in result.errors)

    def test_filename_preserved(self, agent: ValidatorAgent, tmp_path: Path) -> None:
        f = tmp_path / "test_tc001_login.py"
        f.write_text(VALID_SOURCE, encoding="utf-8")
        result = agent.validate_file(str(f))
        assert result.filename == "test_tc001_login.py"

    def test_syntax_error_file(self, agent: ValidatorAgent, tmp_path: Path) -> None:
        f = tmp_path / "test_bad.py"
        f.write_text(SYNTAX_ERROR_SOURCE, encoding="utf-8")
        result = agent.validate_file(str(f))
        assert result.valid is False
        assert any("Syntax error" in e for e in result.errors)

    def test_artefact_file_invalid(self, agent: ValidatorAgent, tmp_path: Path) -> None:
        f = tmp_path / "test_artefact.py"
        f.write_text(UNPARSED_SOURCE, encoding="utf-8")
        result = agent.validate_file(str(f))
        assert result.valid is False


# ------------------------------------------------------------------ #
# validate_batch                                                       #
# ------------------------------------------------------------------ #


class TestValidateBatch:
    def test_returns_result_for_each_file(self, agent: ValidatorAgent, tmp_path: Path) -> None:
        f1 = tmp_path / "test_tc001.py"
        f2 = tmp_path / "test_tc002.py"
        f1.write_text(VALID_SOURCE, encoding="utf-8")
        f2.write_text(VALID_SOURCE, encoding="utf-8")
        results = agent.validate_batch([str(f1), str(f2)])
        assert len(results) == 2

    def test_mixed_valid_invalid(self, agent: ValidatorAgent, tmp_path: Path) -> None:
        f1 = tmp_path / "test_good.py"
        f2 = tmp_path / "test_bad.py"
        f1.write_text(VALID_SOURCE, encoding="utf-8")
        f2.write_text(SYNTAX_ERROR_SOURCE, encoding="utf-8")
        results = agent.validate_batch([str(f1), str(f2)])
        assert results[0].valid is True
        assert results[1].valid is False

    def test_empty_list_returns_empty(self, agent: ValidatorAgent) -> None:
        results = agent.validate_batch([])
        assert results == []

    def test_all_filenames_set(self, agent: ValidatorAgent, tmp_path: Path) -> None:
        f1 = tmp_path / "test_tc001.py"
        f1.write_text(VALID_SOURCE, encoding="utf-8")
        results = agent.validate_batch([str(f1)])
        assert results[0].filename == "test_tc001.py"
